language: ruby
rvm:
 - 2.3.7
 - jruby
 - rbx-3
install:
- bundle install
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $fc5d35cca2c5eaaba33bc3d254f90d5db506a3f9
  keep-history: true
  on:
    branch: gh-pages