language: ruby
rvm:
- 2.0.0
- 1.9.3
- 2.3.7
- jruby-19mode
- rbx-2
before_install:
  openssl aes-256-cbc -K $encrypted_73c56c33471d_key -iv $encrypted_73c56c33471d_iv -in demo-secret-key.enc -out demo-secret-key -d
  - nvm install 8
install:
  - bundle install
cache:
  bundler: true
  directories:
    - node_modules
deploy:
  provider: script
  skip-cleanup: true
  script: gulp deploy
  github-token: cXD0v7D6CnafiQXfABx41AiRfgAnJcjJDaU4Dd7tjeBBNOPqOcXWp5Q+rf4JfVvw0Oe+rw42gmZ491cmHvi5IVEl34P5Tgnpbittdw76egeblp78zfPLMlVRgSDavYWH3q6m6KM4efj/Ls4Jx4Cn+9h6S8jRcXVZzaCjg+MFTzo=
  keep-history: true
  on:
    branch: gh-pages
after_success:
  - eval "$(ssh-agent)"
  - chmod 600 ./deploy.secret.key
  - ssh-add ./deploy.secret.key
  - cd deploy
  - git checkout -B master
  - git add -A
  - git commit --allow-empty -m "$TRAVIS_COMMIT_MSG"
  - echo "Pushing changes"
  - git push git@github.com:donaldboulton/DWB.git gh-pages