# Site wide configuration

url                      : "https://donboulton.com"

profile                  : true
future                   : true
show_docs                : true

google_site_verification : ""
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

google_ad-client         : ""
google_ad-slot           : ""
google_analytics         : ""
