stages:
  - build
  - deploy

build:
  stage: build
  image: starefossen/stretch-slim
  cache:
    paths:
      - node_modules/
      - gems/
  script:
    - npm install
    - npm install gulp -g
    - bundle install --path gems/
    - bundle exec jekyll contentful
    - gulp jekyll:prod
    - gulp minify
  artifacts:
    paths:
      - public
  only:
    - master

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://donboulton.com
  script:
    - apt-get update
    - apt-get install lftp
    - lftp -e "mirror -R build TARGET_DIRECTORY_ON_YOUR_SERVER" -u $USERNAME,$PASSWORD $HOST
  when: manual