[build]
  publish = "_site/"
  command = "npm run build:pwa"
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=360000"
Feature-Policy = "vibrate 'self'; usermedia *; sync-xhr 'self' https://donboulton.com"
Referrer-Policy = "strict-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "style-src 'self'"
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=3153600"
