backend:
  name: git-gateway
  repo: donaldboulton/DWB
  branch: gh-pages
  squash_merges: true
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
    - user

display_url: https://donboulton.com
logo_url: https://donboulton.com/build/firefox_app_60x60.png

media_library:
 name: uploadcare
 config:
   publicKey: a10993e96ebedcb0dd54
   
publish_mode: editorial_workflow

media_folder: "build/img/uploads/" # Folder where user uploaded files should go
public_folder: "/build/img/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie.: "New Post"
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Group", name: "group", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "_events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Id, name: id, widget: number}
      - {label: Title, name: title, widget: string}
      - {label: Start, name: start, widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: End, name: end, widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: allDay, name: allDay, widget: boolean}
      - {label: URL, name: url, widget: string}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "products" 
    label: "Products"
    folder: "_products"
    slug: "{{slug}}"
    create: true 
    fields: 
      - {label: "SKU", name: "sku", widget: "string" }
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Body", name: "body", widget: "string"}  
      - {label: "Slug", name: "slug", widget: "string" }
      - {label: "Layout", name: "layout", widget: "hidden", default: "productdetails"}
  - name: "layouts"
    label: "Layouts"
    folder: "_layouts"
    extension: "html"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: updates
    label: Updates
    files:
      - name: releases
        label: Releases
        file: _data/updates.yml
        fields:
          - name: updates
            label: Releases
            widget: list
            fields:
              - {name: version, label: Version}
              - {name: date, label: Date, widget: date}
              - {name: description, label: Description, widget: markdown}
      - name: notifications
        label: Notifications
        file: _data/notifications.yml
        description: Site-top notifications - publish one at a time
        fields:
          - name: notifications
            label: Notifications
            widget: list
            fields:
              - {label: Title, name: title, widget: string, tagname: h1}
              - {label: Published, name: published, widget: boolean}
              - {label: Loud, name: loud, widget: boolean}
              - {label: Message, name: message, widget: text}
              - {label: URL, name: url, widget: string}
  - name: settings
    label: Settings
    files:
      - name: general
        label: Site Settings
        file: _data/settings.json
        description: General Site Settings
        fields:
          - {label: "Global title", name: site_title, widget: "string"}
          - label: "Post Settings"
            name: posts
            widget: "object"
            fields:
              - {label: "Number of posts on frontpage", name: front_limit, widget: number}
              - {label: "Default Author", name: author, widget: string}
              - {label: "Default Thumbnail", name: thumb, widget: image, class: "thumb"}
      - label: Chart Data
        name: build
        file: _data/builddata.yml
        fields:
          - label: Builds
            name: builds
            widget: list
            fields:
              - {label: Label, name: label, widget: number}
              - {label: Value, name: value, widget: number}
      - name: authors
        label: Authors
        file: _data/authors.yml
        description: Author descriptions
        fields:
          - name: authors
            label: Authors
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}            
              - {label: "Description", name: "description", widget: "markdown"}
